[tox]
envlist = py38-numpy121-pandas135-scipy173, py313-numpy230-pandas230-scipy115

[testenv]
setenv =
    PIP_ONLY_BINARY = *
deps =
    numpy121: numpy==1.21.0
    numpy230: numpy==2.3.0
    pandas135: pandas==1.3.5
    pandas230: pandas==2.3.0
    scipy173: scipy==1.7.3
    scipy115: scipy==1.15.0
    plotly==5.1.0
    tqdm==4.45.0
    pytest

commands = pytest tests

